disabled_rules: # rule identifiers to exclude from running
  - missing_docs
  - unused_closure_parameter
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in
  - empty_count
# Find all the available rules by running:
# swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - DemoSwift
  - DemoSwiftTests
  - DynamicFramework
  - StaticFramework

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300

function_body_length:
  - 200 # warning
  - 300 # error

function_parameter_count:
  - 10 # warning
  - 15 # error

large_tuple:
  - 6 # warning
  - 12 # error

# they can set both implicitly with an array
type_body_length:
  - 300 # warning
#  - 400 # error

# or they can set both explicitly
file_length:
  warning: 1000
  error: 2000

cyclomatic_complexity:
  - 15 # warning
  - 30 # error

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - T
    - E

identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - vc
    - id
    - in
    - kf
    - to
    - x
    - y
    - z
    - i
    - j
